 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
    build-windows:
     executor: win/vs2019
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet restore
       - run: dotnet build




