 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
    docker:
        -image: mcr.microsoft.com/dotnet/core/sdk:2.2
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet restore 
       - run: dotnet build
       - run: dotnet run




